language: node_js
node_js:
- '4'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install -g gulp
script: gulp build
before_deploy: cd dist
deploy:
  provider: npm
  email: joe.lekie@gmail.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: nFO6T/q3VnPPVzZod0xXXOw24XB17jT12qkPiBnMZDUlWWFUWNHQNUWPkNWPFF5ik25DxJjO/ya1Do7wWkZt2gS+JMaN8XXTps55Q3Fme11jeIRNEpAbiPc4ybGfcsm0trvFzSD9Vy31Lb9Ll5401elE8TNqVFq0Z/4MxzlScQV+cseeX46kJxiQjm92zVyXY49qfQsPbsMgQqKZjjCBvNK3b4bBTMfHw2PfmcDplv7H8JEOOiKBnrBFxkwxRG9a071EJAVJuHb9epyel4tCx48bwbw6l3dvpZEUzhEaeXKDjevzFyScAus0tldEYP2wKne0wsTDfzZ4o7MKYjvfhh1DSXDCRWvqNcWdCqCQg/jkZq555ELYAq+7Nkwi5LG4AHaReuVZIU3wECoDqlltbO9mN7E/x0/RVNKG0pSdegkjYb2rAB+7TCAb3IsStXDUzGjZt9rjvO8oitNVY5MS/jL7s7czxCCc9uzd6dXWBBMOlV2gp1D7NrNzjUmuIfRnE1Uwxv2qYeviSRXfIJyp4MYCgHbAPFGdC4wqaOVSVATy+MTPNGFpj0dm+sZHRDVlo8A5drEStVP5AOPdDB/EbmpMh8TM1R1iK+N6fa0VI/aeMkAkrhJOEj7uaejJKJC/8gbooI+V5v0cU0Y28wg2UF+QGg3VVWS8lAGmQN6CYk8=
